### ISSUE TITLE
suggests update of a gem to version incompatible with gem that depends on it

### ISSUE THREAD

**Issue by Incanus3** [wireframe/bundler-updater#2]
e.g. this is a part of my Gemfile.lock:

```
    sprockets (2.11.0)
      hike (~> 1.2)
```

but bundler-updater asks if I want to upgrade hike to 2.1.3, which will most probably break sprockets.

It would be nice if there was an option to upgrade only explicit dependencies - i.e. those in Gemfile. Still answering y/n questions while looking at Gemfile.lock is much better than doing this manually, so thanks a lot for this nice utility.

**Comment by wireframe** [comment]
just an FYI:
in this case, bundler-updater will _ask_ you to update hike, but since sprockets does _not_ allow version 2.1.3, it won't actually update the gem past the highest allowed version.

sorry if that's confusing, and I'd love to hear ideas on how to improve (and patches are always welcome)

**Comment by Incanus3** [comment]
Oh, then I guess that's fine. I've looked at the code now and I see you're
already partitioning the gems into gemfile_specs and dependency_specs, but
you're then joining the arrays together again, so it shouldn't be hard to
iterate only over gemfile_specs. I've no experience with thor, and not much
time to study it now, but passing the option there should be possible, so
may be I'll look at it later. Thanks for the quick reply.
