### ISSUE TITLE
Error running with bundler 1.6.4

### ISSUE THREAD

**Issue by niossifo** [wireframe/bundler-updater#3]
The result:

$ bundler-updater
Scanning for outdated gems...
/var/lib/gems/2.0.0/gems/bundler-updater-0.0.3/lib/bundler/updater/cli.rb:59:in `all_gem_specs': undefined method`silence' for #Bundler::UI:0x0000000261a150 (NoMethodError)
        from /var/lib/gems/2.0.0/gems/bundler-updater-0.0.3/lib/bundler/updater/cli.rb:26:in `outdated_gems_to_update'
        from /var/lib/gems/2.0.0/gems/bundler-updater-0.0.3/lib/bundler/updater/cli.rb:9:in`update'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`each'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`invoke_all'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
        from /var/lib/gems/2.0.0/gems/bundler-updater-0.0.3/bin/bundler-updater:4:in `<top (required)>'
        from /usr/local/bin/bundler-updater:23:in`load'
        from /usr/local/bin/bundler-updater:23:in `<main>'

I have bundler 1.6.4.

**Comment by wireframe** [comment]
i believe the silence method was added in bundler 1.8.  
http://www.rubydoc.info/github/carlhuda/bundler/Bundler/UI/Shell#silence-instance_method

Bundler 1.6.4 was released july 2014 and i don't have it on my radar for support.  if you'd like to contribute a pull request to add compatibility and can test for regressions, let me know.

**Comment by niossifo** [comment]
Why wouldn't you specify dependency in your Gemfile?

**Comment by wireframe** [comment]
patches are welcome of course.  

I find it overly restrictive to "require" gem versions for libraries.  I do my testing with the latest versions, but that does not prevent most libraries from working with relatively older version.
